// Generated by CoffeeScript 1.9.0
(function() {
  var $closenewroom, $createroom, $newroom, $popup, $roomname;

  $newroom = $('#new_room');

  $popup = $('#popup');

  $roomname = $('#newroomname');

  $createroom = $('#createroom');

  $closenewroom = $('#popup .close');

  $newroom.click($.fn.show.bind($popup));

  $closenewroom.click($.fn.hide.bind($popup));

  $createroom.click(function() {
    return $.ajax({
      method: 'PUT',
      url: 'room',
      data: {
        name: $roomname.val()
      }
    }).done(function(data) {
      return console.log(data);
    });
  });

}).call(this);
